# Generated by Django 2.2 on 2019-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12)),
                ('date_of_visiting', models.CharField(max_length=11, null=True)),
                ('symptoms', models.TextField(max_length=300, null=True)),
                ('drugs', models.TextField(max_length=300, null=True)),
                ('dosage', models.TextField(max_length=300, null=True)),
                ('tests_to_be_done', models.TextField(max_length=300, null=True)),
                ('date_for_revisit', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('aadhar_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
