# Generated by Django 2.2 on 2019-10-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='aadhar_no',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='record',
            name='aadhar_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
