# Generated by Django 2.1.1 on 2019-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_files_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='prescription_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
